
crds:
  install: true   # install CRDs with the chart
  keep: false     # remove CRDs on helm uninstall
  
server:
  service:
    type: ClusterIP  # or NodePort/ClusterIP as needed
  extraArgs:
    - --insecure  # only for development

configs:
  secret:
    argocdServerAdminPassword: "$2a$10$lgcvwdvggWeLl1AN14NWsePcWQczWHRQH2eiUNL9w/gN6NaelDl.G"  # Optional password override
    

